Bank/Bank/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_app.urls')),
    path('bank_app/',include('bank_app.urls')),

]

Bank/bank_app/urls.py
from django.urls import path
from . import views

app_name = "bank_app"


urlpatterns = [
    path('', views.home, name="home"),
    path('deposit/', views.DepositView.as_view(), name="deposit"),
    path('withdraw/', views.WithdrawView.as_view(), name="withdraw"),
    path('report/', views.ReportView.as_view(), name="report"),
    path('transfer_amount/', views.TransferAmountView, name="transfer")
]

Bank/bank_app/models.py
from django.db import models
from user_app.models import User
from django.db.models import Sum

# Create your models here.


class Transction(models.Model):

    TRANSACTION_TYPE_CHOICES = (
        ('Deposit', 'Deposit'),
        ('Withdrawal', 'Withdrawal'),
        ('Transfer', 'Transfer'),
        ('Receive', 'Receive'),
    )

    AMOUNT_TYPE_CHOICES = (
        ('Credit', 'Credit'),
        ('Debit', 'Debit'),
    )
    amount_type = models.CharField(
        max_length=20, choices=AMOUNT_TYPE_CHOICES, null=True, blank=True)
    transction_type = models.CharField(
        max_length=20, choices=TRANSACTION_TYPE_CHOICES)
    current_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='transactions')
    amount = models.DecimalField(decimal_places=2, max_digits=12)

    def __int__(self):
        return self.amount

    def save(self, *args, **kwargs):
        if self.transction_type in ['Deposit', 'Receive']:
            self.amount_type = Transction.AMOUNT_TYPE_CHOICES[0][0]
        else:
            self.amount_type = Transction.AMOUNT_TYPE_CHOICES[1][1]
        super().save(*args, **kwargs)

    # @classmethod                                                               //class decorator
    # def calculate_balance(cls, user):
    #     transactions = cls.objects.filter(user=user)
    #     balance = 0
    #     for transaction in transactions:
    #         if transaction.transaction_type == 'Deposit' or transaction.transaction_type == 'Receive':
    #             balance += transaction.amount
    #         elif transaction.transaction_type == 'Withdrawal' or transaction.transaction_type == 'Transfer':
    #             balance -= transaction.amount
    #     return balance

    # def calculate_balance(user):                                                //function
    #     transactions = Transction.objects.filter(user=user)
    #     balance = 0
    #     for transaction in transactions:
    #         if transaction.amount_type == 'Credit':
    #             balance += transaction.amount
    #         elif transaction.amount_type == 'Debit':
    #             balance -= transaction.amount
    #     return balance

    # @property                                                                    //property using for loop
    # def balance(self):
    #     transactions = Transction.objects.filter(user=self.user)
    #     balance = 0
    #     for transaction in transactions:
    #         if transaction.amount_type == 'Credit':
    #             balance += transaction.amount
    #         elif transaction.amount_type == 'Debit':
    #             balance -= transaction.amount
    #     return balance

    @property
    def balance(self):
        credits = Transction.objects.filter(
            user=self.user, amount_type="Credit").aggregate(balance=Sum('amount'))['balance'] or 0

        debit = Transction.objects.filter(
            user=self.user, amount_type="Debit").aggregate(balance=Sum('amount'))['balance'] or 0
        balance = credits - debit
        return balance

Bank/bank_app/forms.py
from django import  forms
from .models import Transction
from django.core.exceptions import ValidationError

class DepositForm(forms.ModelForm):
    class Meta:
        model = Transction
        fields = ("amount",)

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if not amount>0:
            raise ValidationError("Amount should be Positive Number")
        return amount

class WithdrawForm(forms.ModelForm):
    class Meta:
        model = Transction
        fields = ("amount",)
        
    def clean_amount(self):
        amount = self.cleaned_data['amount']
        if not amount>0:
            raise ValidationError("Amount should be Positive Number")
        return amount

Bank/bank_app/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from user_app.models import User

from .forms import DepositForm, WithdrawForm
from .models import Transction


def home(request):
    # balance = Transction.calculate_balance(request.user)
    transaction = Transction.objects.filter(user=request.user).first()
    if transaction is not None:
        balance = transaction.balance
    else:
        balance = 0
    return render(request, "home.html", {"balance": balance})


class DepositView(SuccessMessageMixin, CreateView):
    form_class = DepositForm
    template_name = "deposit.html"
    success_url = reverse_lazy('bank_app:deposit')
    success_message = "Successfully Deposit Amount !"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.transction_type = Transction.TRANSACTION_TYPE_CHOICES[0][0]
        return super().form_valid(form)


class WithdrawView(SuccessMessageMixin, CreateView):
    form_class = WithdrawForm
    template_name = "withdraw.html"
    success_url = reverse_lazy('bank_app:withdraw')
    success_message = "Successfully Withdraw Amount !"

    def form_valid(self, form):
        amount = self.request.POST.get("amount")
        balance = Transction.calculate_balance(self.request.user)
        if balance < int(amount):
            messages.error(
                self.request, "Low balance. Unable to withdraw amount.")
            return self.form_invalid(form)
        form.instance.user = self.request.user
        form.instance.transction_type = Transction.TRANSACTION_TYPE_CHOICES[1][1]
        return super().form_valid(form)


class ReportView(ListView):
    model = Transction
    template_name = "report.html"
    context_object_name = "tran_report"

    def get_queryset(self):
        trans = Transction.objects.all()
        return trans if self.request.user.is_manager == True else Transction.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        transaction = Transction.objects.filter(
            user=self.request.user).first()

        if transaction and transaction.balance:
            context['balance'] = transaction.balance
        else:
            context['balance'] = 0
        return context


def TransferAmountView(request):
    if request.method == "POST":
        try:
            send = request.POST.get("send")
            amount = request.POST.get("amount")

            with transaction.atomic():
                balance = Transction.objects.filter(
                    user=request.user).first().balance
                # balance = Transction.calculate_balance(request.user)
                if balance > int(amount):
                    trans = Transction.objects.create(
                        transction_type=Transction.TRANSACTION_TYPE_CHOICES[2][0], user=request.user, amount=int(amount))
                else:
                    return render(request, "transfer.html", {'error_message': 'Insufficient Balance!'})

                user2 = User.objects.filter(Q(account_number=send) & ~Q(
                    account_number=request.user.account_number)).last()
                trans = Transction.objects.create(
                    transction_type=Transction.TRANSACTION_TYPE_CHOICES[3][0], user=user2, amount=int(amount))
                messages.success(
                    request, 'Successfully your Amount is transfered')
        except Exception as e:
            print(e)
            messages.error(request, 'Account Number does not Exists!')
    return render(request, "transfer.html")

Bank/bank_app/templates/b_base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
    nav .navbar-nav li a {
      color: white !important;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg  bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand " href="#">Welcome To Bank</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <h5 style="font-style:oblique;"><a class="nav-link active" aria-current="page" href="{% url 'bank_app:home' %}">Home</a></h5>
          </li>
          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'bank_app:deposit' %}">Deposit</a></h5>
          </li>

          <li class="nav-item">
            <h5> <a class="nav-link" href="{% url 'bank_app:withdraw' %}">Withdraw</a></h5>
          </li>

          <li class="nav-item">
            <h5> <a class="nav-link" href="{% url 'bank_app:transfer' %}">Transfer Amount</a></h5>
          </li>
          
          <li class="nav-item">
            <h5> <a class="nav-link" href="{% url 'bank_app:report' %}">Transaction Report</a></h5>
          </li>

        <li class="nav-item">
            <h5> <a class="nav-link" href="/">Logout</a></h5>
          </li>

          <li class="nav-item">

            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </li>
        </ul>
        
        <li class="nav-item">
          <h5> <a class="nav-link" >{{request.user}}</h5>
        </li>
          

      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %} <br>


 
</body>

</html>


<!-- =======End New Footer ======= -->

Bank/bank_app/templates/deposit.html
{% extends 'b_base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div style="background-color: bisque; height:max-content">
<center>

{% if messages %}
{% for message in messages %}
<div>{{ message}}</div>
{% endfor %}
{% endif %}
    

<div>
    <form action="{% url 'bank_app:deposit' %}" method="POST" style="width: 300px; height:1000px;">
        {% csrf_token %}
        <br><br><br>
        <div>Deposit Money to your Account </div> <br>
        {{form|crispy}}  <br>
        <button type="submit" class="btn btn-danger">Submit</button>
    </form>
</div>

</center>
</div>
{% endblock %}

Bank/bank_app/templates/home.html
{% extends 'b_base.html' %}

{% block  content %}

<h5>Your Account balance :  &#8377;{{balance}} </h5>

<!-- <a href="" class="btn btn-warning">Check balance</a> -->
{% endblock %}

Bank/bank_app/templates/report.html
{% extends 'b_base.html' %}


{% block content %}

  <div style="background-color:rgb(173, 217, 234);color:black">

<br>
<center>
<h2>Transaction Report</h2> <br><br>
</center>
    <table class="mx-auto w-full mt-8 border-collapse">
        <tr>
          <th class=" border border-black px-4 py-2">Date</th>
          <th class=" border border-black px-4 py-2" >Transction Type</th>
          <th class=" border border-black px-4 py-2">Credit</th>
          <th class=" border border-black px-4 py-2">Debit</th>
        </tr> <br><br>

        {% for report in tran_report %}
        <tr>
          <td class=" border border-black px-4 py-2">{{report.current_time}}</td>
          <td class=" border border-black px-4 py-2">{{report.transction_type}}</td>

          {% if report.transction_type == 'Deposit' or report.transction_type == 'Receive' %}
            <td class=" border border-black px-4 py-2">{{report.amount}}</td>
            <td class="border border-black px-4 py-2"></td>
          {% else %}
          <td class="border border-black px-4 py-2"></td>
          <td class="border border-black px-4 py-2">{{ report.amount }}</td>
          {% endif %}

        </tr> <br>
        {% endfor %}

        <tr class="bg-gray-600 text-black" >
          <th class="border border-blue-900 px-4 py-2 text-right" colspan="3">Current Balance</th>
          <th class="border border-blue-900 px-4 py-2 text-right" colspan="3">{{balance}}</th>
        </tr>
      </table>
</div>
{% endblock %}

Bank/bank_app/templates/transfer.html
{% extends 'b_base.html' %}

{% block content %}


<form method="POST" action="">
{% csrf_token %}
<center>    

{% if messages %}
<div class="alert alert-info">
    {% for message in messages %}
        {{message}}
    {% endfor %}
</div>
{% else %}
<div style = "background-color:pink;">{{error_message}}</div>
{% endif %} <br><br><br>


<label>To : </label>
<input type="text"  placeholder="Enter Account Number" name="send"> <br><br>

<label>Amount :</label>
<input type="text"  placeholder="Enter Amount" name="amount"> <br><br>

<button type="submit">Submit </button>

</center>
</form>
{% endblock %}

Bank/bank_app/templates/withdraw.html
{% extends 'b_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div style="background-color: bisque; height:max-content">
<center>


{% if messages %}
{% for message in messages %}
<div style = "background-color:pink;">{{ message}}</div>
{% endfor %}
{% else %}
<div style = "background-color:pink;">{{error_message}}</div>
{% endif %}
    
<div>
    <form action="{% url 'bank_app:withdraw' %}" method="POST" style="width: 300px; height:1000px;">
        {% csrf_token %}
        <br><br>
        <div>Withdraw Money from Your Account</div> <br>
        {{form|crispy}}  <br>
        <button type="submit" class="btn btn-danger">Submit</button>
    </form>
</div>
</center>
</div>

{% endblock %}