Bank/Bank/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_app.urls')),
    path('bank_app/',include('bank_app.urls')),

]

Bank/user_app/urls.py
from django.urls import path
from. import views

app_name = "user_app"

urlpatterns = [
    path('',views.home),
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',views.LoginView.as_view(),name='login')

]

Bank/user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .manager import UserManager

# Create your models here.


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    account_number = models.IntegerField(unique=True,null=True)
    is_manager = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = []

    def __int__(self):
        return self.email

    # def save(self, *args, **kwargs):
    #     self.account_number = random.randrange(100000000000,999999999999)
    #     super().save(*args, **kwargs)

Bank/user_app/forms.py
from django import  forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email","password1","password2","first_name","last_name")

    def clean_account_number(self):
        account_number = str(self.cleaned_data['account_number'])
        if len(account_number)!=12:
            raise ValidationError("Account Number should be of 12 digit")
        return account_number
    
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "password")

Bank/user_app/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from . forms import SignupForm , LoginForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import authenticate, login
from django.contrib import messages
import random

# Create your views here.

def home(request):
    return render(request,"base.html")

class SignupView(SuccessMessageMixin,CreateView):
    form_class = SignupForm
    template_name = "signup.html"
    success_url = reverse_lazy('user_app:signup')

    def form_valid(self,form):
        account_number = random.randrange(100000000000,999999999999)
        form.instance.account_number = account_number
        success_message = f"Successfully signed up!  Your Account Number is {account_number}"
        messages.success(self.request, success_message)
        return super().form_valid(form)

class LoginView(CreateView):
    form_class = LoginForm
    template_name = "login.html"

    def post(self,request):
        email =  request.POST.get("email")
        password = request.POST.get("password")
        
        user = authenticate(email=email,password=password)
        if user:
            login(request, user)
            return redirect("/bank_app/")
        return HttpResponse("You have not signup ! please signup first")

Bank/user_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <style>
    nav .navbar-nav li a {
      color: white !important;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg  bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand " href="#">Bank</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <h5 style="font-style:oblique;"><a class="nav-link active" aria-current="page" href="/">Home</a></h5>
          </li>
          <li class="nav-item">
            <h5><a class="nav-link" href="{% url 'user_app:signup' %}">Signup</a></h5>
          </li>

          <li class="nav-item">
            <h5> <a class="nav-link" href="{% url 'user_app:login'%}">Login</a></h5>
          </li>
          
          <li class="nav-item">

            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </li>

        </ul>


      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock %} <br>


 
</body>

</html>


<!-- =======End New Footer ======= -->

Bank/user_app/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div style="background-color: bisque; height:max-content">
<center>

{% if messages %}
{% for message in messages %}
<div>{{ message|safe }}</div>
{% endfor %}
{% endif %}

     <div>
        <form action="{% url 'user_app:login' %}" method="POST" style="width: 300px; height:1000px;">
            {% csrf_token %}

            <br>
            <h2>Login here </h2>
            <br>

            {{form|crispy}}  <br>
            <button type="submit" class="btn btn-danger">login</button>

        </form>
    </div>

</center>
</div>

{% endblock %}

Bank/user_app/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div style="background-color: bisque; height:max-content">

<center>

{% if messages %}
{% for message in messages %}
<div style = "background-color:pink;">{{ message}}</div>
{% endfor %}
{% else %}
{{error_message}}
{% endif %}

     <div>
        <form action="{% url 'user_app:signup' %}" method="POST" style="width: 300px; height:1000px;">
            {% csrf_token %}

            <br>
            <h2>Registration</h2>
            <br>

            {{form|crispy}}  <br>
            <button type="submit" class="btn btn-danger">SignUp</button>

        </form>
    </div>

</center>
</div>

{% endblock %}